### ISSUE TITLE
Function for Project -> Git Sha

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_version_checker#24]
It would nice to have a small function that allows you to just figure out the git SHA of all the tools you current are using.

Effectively, this would look at the currently installed tool version (respecting the virtual environment, if one is active), and returning the git sha value for each esm-tools related project. This could look something like the following:

```python
import esm_version_checker.determine_shas

git_shas = determine_shas()
print(git_shas)
```
Gives back:
```
{
"esm_tools": "140d197",
"esm_runscripts": "something",
}
```
and so on. We indirectly do this anyway, so it should not be too hard.

**Comment by denizural** [comment]
This is exactly what I am planning to do. I just have some stuff lying around in my TODO list. Will do it asap.

**Comment by pgierz** [comment]
No longer relevant as of monorepo, closing...
